name: Creación docker image

on:
  # se ejecuta el flujo con cada push y pull request
  # o haciendo clic desde las opciones de Github Actions
  [push, pull_request, workflow_dispatch]
  
jobs:
  build:

    # se ejecuta en Ubuntu Linux
    runs-on: ubuntu-latest

    # acciones a ejecutar
    steps:
    - name: Descarga el código fuente
      uses: actions/checkout@v2
    - name: Login en Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Configuracion Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      

    - name: Crear y subir imagen back
      id: docker-build-back
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./python/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/py-crud-image:latest   

    - name: Crear y subir imagen front
      id: docker-build-front
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./angular/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/ng-app-image:latest   

    - name: Digest de la imagen
      run: echo ${{steps.docker_build.outputs.digest}}
